sudo: required
dist: trusty
language: python
python:
- '2.7'
- pypy
services:
  - docker
env:
  global:

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
